export default function ExperiencePage() {
  // Define the job experiences
  const jobExperiences = [
    {
      title: "Senior Cybersecurity Analyst",
      company: "SecureTech Solutions",
      period: "2021 - Present",
      responsibilities: [
        "Lead a team of security analysts in monitoring and responding to security incidents across the organization.",
        "Implemented a new Security Information and Event Management (SIEM) system, reducing incident response time by 35%.",
        "Conducted regular vulnerability assessments and penetration tests to identify and mitigate security risks.",
        "Developed and maintained security policies, procedures, and standards in compliance with industry regulations."
      ]
    },
    {
      title: "Cybersecurity Analyst",
      company: "DataGuard Inc.",
      period: "2018 - 2021",
      responsibilities: [
        "Performed security monitoring, analysis, and incident response for a Fortune 500 financial services company.",
        "Investigated and responded to security alerts generated by intrusion detection systems and SIEM tools.",
        "Participated in 24x7 on-call incident response rotation.",
        "Conducted security assessments of new applications and infrastructure before deployment."
      ]
    },
    {
      title: "Network Security Engineer",
      company: "GlobalDefense Networks",
      period: "2016 - 2018",
      responsibilities: [
        "Designed and implemented secure network infrastructure, including firewalls, IDS/IPS, and VPN solutions.",
        "Performed network vulnerability assessments and remediation activities.",
        "Maintained network security devices and implemented security patches and updates.",
        "Collaborated with IT teams to ensure security best practices were followed in network design and implementation."
      ]
    },
    {
      title: "IT Security Specialist",
      company: "TechSecure Solutions",
      period: "2014 - 2016",
      responsibilities: [
        "Managed user access control systems and identity management platforms.",
        "Conducted security awareness training for employees.",
        "Assisted in security incident investigations and remediation.",
        "Performed regular security scans and audits of company systems and networks."
      ]
    }
  ];

  return (
    <section className="container py-12">
      <h1 className="text-3xl font-bold mb-8">Professional Experience</h1>

      <div className="space-y-12">
        {jobExperiences.map((job, index) => (
          <div key={`${job.company}-${index}`} className="border-l-4 border-accent pl-6">
            <div className="flex flex-col md:flex-row md:justify-between mb-2">
              <h2 className="text-xl font-bold">{job.title}</h2>
              <span className="text-muted-foreground">{job.period}</span>
            </div>
            <h3 className="text-lg text-accent mb-4">{job.company}</h3>
            <ul className="list-disc pl-5 space-y-2">
              {job.responsibilities.map((responsibility, respIndex) => (
                <li key={`${job.company}-resp-${respIndex}`} className="text-muted-foreground">
                  {responsibility}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </section>
  );
}
